defaults: &defaults
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  schema_search_path: public
  encoding: utf8
  template: template0
  pool: 10 
  timeout: 5000

development:
  <<: *defaults
  database: kyck_development

test:
  <<: *defaults
  database: kyck_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *defaults
  database: kyck_production


